### ISSUE TITLE
KLG/LKM - visning av aktuelle trinn per type

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1045]
**Describe the bug**
Klasserings langs aktuelle LKM/KLG for enkelte grunntyper både NA og NA viser hele range for hovedtype, og ikke den aktuelle grunntypen. Mønsteret synes å være at alle kartleggingsenheter/grunntyper med nr. 1 viser hele hovedtypens 'range', mens øvrige kartleggingsenheter/grunntyper viser kodens aktuelle trinn. langs lkm/KLG

 
**To Reproduce**
1. Eksempel på feil visning: 
https://nin.artsdatabanken.no/Natur_i_Norge/Landskap/Innlandslandskap/Innlands%C3%A5s-_og_fjellandskap/Dalformet_%C3%A5s-_og_fjellandskap_under_skoggrensen
https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem/Limniske_vannmasser/Elvevannmasser/Kalkfattige_klare_roligflytende_eller_hurtigstr%C3%B8mmende_elvevannmasser
https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem/Fastmarkssystemer/Fastmarksskogsmark/Bl%C3%A5b%C3%A6r-_og_b%C3%A6rlyngskoger

**Comment by bjornreppen** [comment]
phew
