### ISSUE TITLE
Natursystem - kartleggingsenheter og visning i kart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1061]
**Describe the bug**
I dag viser vi alle underliggende koder (1 nivå ned) i kartet. Eks, Er man på Natursystem, viser vi alle hovedtypegruppene, er man på en hovedtype, viser 1:20000 enheter i kartet.

Dette fungerer fint, men blir ulogisk når man har klikket seg inn på det laveste nivå det foreligger data. 

 
**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem/Fastmarkssystemer/Fastmarksskogsmark/Bl%C3%A5b%C3%A6r-_og_b%C3%A6rlyngskoger/B%C3%A6rlyngskog'
2. Click on 'statistikk'
3. her ser vi at det finnes data i statitikk ,men ikke i kartet.

**Expected behavior**
å se de data som finnes på koden (selv om dette bryter med logikken) 

PS! Tar gjerne en diskusjon i morgen!

**Screenshots**

![image](https://user-images.githubusercontent.com/31729342/53788919-6a387180-3f23-11e9-81f0-417a1e08babd.png)

**Additional context**

**Comment by runningbones** [comment]
Løvnodeutfordring?

**Comment by bjornreppen** [comment]
Nei, ser ut som noe annet er feil, her finnes det kart: https://data.artsdatabanken.no/Natur_i_Norge/Natursystem/Fastmarkssystemer/Fastmarksskogsmark/Bl%C3%A5b%C3%A6r-_og_b%C3%A6rlyngskoger/B%C3%A6rlyngskog/

**Comment by bjornreppen** [comment]
![image](https://user-images.githubusercontent.com/281359/53803905-6407bc80-3f46-11e9-98db-acab5e355784.png)
