### ISSUE TITLE
Klikk i kart - nord for fastlandsnorge

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1062]
**Describe the bug**
Klikk i kart nord for norsk fastland gir feilmelding.

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem/Lokale_komplekse_milj%C3%B8variabler?lng=20.053712725639347&lat=75.2901216366799'
2. See error

**Comment by runningbones** [comment]
Løvnodeutfordring?

**Comment by bjornreppen** [comment]
Viser fortsatt tomt vindu ved klikk.. prøv å vise en melding?
