### ISSUE TITLE
Verneområder - kun visning av alle objekt samtlidig

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1063]
**Describe the bug**
Klarer ikke å vise kun 1 verneområde, (kun alle). 

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Naturvernomr%C3%A5de'
2. Click on 'et tilfeldig verneområde i venstremeny'
3. See error

**Expected behavior**
å se kun det aktuelle vernepområdet

**Comment by runningbones** [comment]
Løvnodeutfordring?

**Comment by bjornreppen** [comment]
Gjenstår å lage kartfiler per område, tomt her: https://data.artsdatabanken.no/Naturvernomr%C3%A5de/Svaet_dyrefredningsomr%C3%A5de/

**Comment by runningbones** [comment]
Men det ligger kartfiler per vernekategori: https://data.artsdatabanken.no/Naturvernomr%C3%A5de/Verneform/Nasjonalpark/index.html
