### ISSUE TITLE
Katalogstruktur/navnsetting av katalogelement i venstremeny - Klassifisering

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1074]
'Klassifisering': Noe forvirrende da denne i realiteten visere hvor i hierarkiet du er, samt høyere klassifisering. "Inndeles i" er det samme treet, men er i tillegg en kombinasjon av "legend" og videre filtrering. Foreslår at 'klassifisering'-elementet ersattes av lenkene vi brukte i forrige versjon:
![image](https://user-images.githubusercontent.com/31729342/53952975-862e4580-40d2-11e9-9cd3-c74be221a76b.png)

**Comment by bjornreppen** [comment]
Enig i det. Utfordringen (og årsaken til at jeg flytta dem ned) er å tilfredsstille kravene til universell utforming. https://uu.difi.no/krav-og-regelverk/losningsforslag-web/klikkeflate-navigasjon

Bør være mulig å finne en middelvei, men jeg har ikke noe godt forslag pr nå

**Comment by runningbones** [comment]
Om vi skal ha med elementet bør vi ihvertfall "snu" rekkefølge i hierarkiet, katalog øverst. Henger litt dårlig sammen med "inndeles i! nå 
![image](https://user-images.githubusercontent.com/31729342/53953956-12416c80-40d5-11e9-95f0-e04115ddec53.png)

**Comment by runningbones** [comment]
Skulle vært lukket for lenge siden:)
