### ISSUE TITLE
Katalog - forslag til nye navn på element

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1075]
Katalog | Katalogelement | Element | Nytt_navn | Merknad
-- | -- | -- | -- | --
Natur i Norge | Natursystem | Klassifisering |   | Vurder om dette elementet kan erstattes av å gjenbruke lenkekomponent i   tidligere versjon
Natur i Norge | Natursystem | Beskrivelse |   |  
Natur i Norge | Natursystem | Statistikk |   |  
Natur i Norge | Natursystem | Inndelt i |   | Bruk riktig NiN terme, ikke typer på alt. Eks hovedtypegrupper,   hovedtyper, kartlegginigsenheter, trinn etc
Natur i Norge | Natursystem | Gradienter | Miljøvariabler - LKM |  
Natur i Norge | Natursystem | Beskrives av | Beskrivelsessystem |  
Natur i Norge | Natursystem | inndeles ved hjelp av |   | Kan kanskje fjernes, er i realiteten det samme som gradienter, bare med   ett klikk mere?
Natur i Norge | Natursystem | Lokale egenskaper |   | Vurder relevans! Må ha andre navn hvis med videre. 
Natur i Norge | Natursystem | Publiseres av | Datakilde |  
Natur i Norge | Landskap | Klassifisering |   | Vurder om dette elementet kan erstattes av å gjenbruke lenkekomponent i   tidligere versjon
Natur i Norge | Landskap | Beskrivelse |   |  
Natur i Norge | Landskap |   | Statistikk | Denne kan med fordel komme inn på LA!
Natur i Norge | Landskap | Inndelt i |   |  
Natur i Norge | Landskap | Gradienter | Landskapsgradienter (KLG) |  
Natur i Norge | Landskap | Egenskaper |   |  
Natur i Norge | Landskap | Defineres av |   |  
Datakilde | Oraganisasjon | Inndelt i |   | Organisasjon
Administrativt område | Fylker | inndelt i |   | Fylker
Administrativt område | Kommuner | inndelt i |   | Kommuner

**Comment by bjornreppen** [comment]
Kjempebra, med unntak av Beskrivelsessystem som etter min mening burde premieres for minst beskrivende beskrivelse.  Jeg forstår fortsatt ikke hva BS (!?) beskriver  til forskjell fra LKMer til tross for 3 års opplæring.  Er årsaken til at BS er puttet i en separat bås at de ikke blir brukt som byggesteiner for typene?  Ikke veldig intuitivt og kanskje ikke veldig godt forklart på våre sider? "Natursysteminndelingen utgjør sammen med beskrivelsessystemet en helhet i NiN."  OK?  Hm.  LKMer forstår jeg heller ikke, hvorfor kalles de lokale og hvorfor de kalles komplekse.  Beskriver ikke beskrivelsessystem lokale egenskaper? Hva gjør en miljøvariabel lokal?  Burde vi hatt litt forklaring rundt disse?  Er kalk eller permafrost vanvittig komplekse variabler?  ...eller blir det først komplekst når de settes sammen i en n-dimensjonal kube?  Jeg er ihvertfall meget fornøyd med forslag til nytt navn på LKM - Miljøvariabler

**Comment by bjornreppen** [comment]
"Variasjon som ikke kan beskrives ved hjelp av uLKM er sortert på ni grupper av Kilder til variasjon. Variasjonen langs disse beskrives ved bruk av variabler som er definert så presist som mulig, men som er delt i klasser eller trinn uten noen direkte referanse til hvor mye variasjon i artssammensetning de gir opphav til." https://maps.artsdatabanken.no/Natur_i_Norge/Natursystem/Beskrivelsessystem/index.html

Kan det være så enkelt som at BS er en sekkepost med miljøvariabler som vi mangler vitenskapelige referanser til hvordan de påvirker variasjon i artssammensetning?    :confused

**Comment by runningbones** [comment]
Du nærmer deg kjernen @bjornreppen 👍 . BS er all observerbar variasjon i miljøbetingelser som IKKE bidrar til signifikant endring av artsinnventar (og dermed gir oppgav til typer), men forøvrig enig i refleskjoner rundt semantikken beskrivelsessystem; å sette sammen to intetsigende termer gir ikke nødvendigvis et presist begrep...

**Comment by runningbones** [comment]
Lekkert!
