### ISSUE TITLE
ultramafisk - mangler under NGU-datasett

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1076]
**Describe the bug**

DAtasettet ligger i Nin-kart
https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem/Lokale_komplekse_milj%C3%B8variabler/Berggrunn_med_avvikende_kjemisk_sammensetning/Ultramafisk

Men ikke under https://nin.artsdatabanken.no/Datakilde/Norges_Geologiske_Unders%C3%B8kelse

**Comment by bjornreppen** [comment]
Jeg misforsto først problemet her.  Datasettkoblingen lå der, men til nivået over, "Berggrunn med avvikende..."  Endret koblingen til å peke rett på ultramafisk  https://github.com/Artsdatabanken/kverna/blob/master/kildedata/Datakilde/or_datasett.json

I tillegg endret jeg slik at alle undertyper også ble koblet direkte tilbake til datakilde, slik at man ikke lenger må navigere seg opp treet til et rotpunkt for å finne kobling til datakilde.  Usikker på om dette var en god ide?
