### ISSUE TITLE
Klikk i kart - gir av og til kryptiske feil i link til LA-type

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1104]
**Describe the bug

Klikk i kart: av og til fører lenken i venstremarg (LA) til en annen type enn den typen som står oppført i punktet.

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/?lng=9.124205822145669&lat=62.074867088480985'
2. Click on 'lenken til landskapstypen'
3. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/31729342/54116314-c2bdb200-43ee-11e9-9793-715bf035d5f0.png)

![image](https://user-images.githubusercontent.com/31729342/54116349-d0733780-43ee-11e9-89b8-69464cd0850d.png)

**Comment by bjornreppen** [comment]
Ikke helt solid den der.  Gjort en ny midlertidig hack for å fikse.

Den langsiktige løsningen jeg hadde på blokka var endring av søke-API:  https://github.com/Artsdatabanken/nin-innsyn/issues/1106 - men jeg hadde ikke så lyst til å begynne med det akkurat nå.

**Comment by bjornreppen** [comment]
Fixed
