### ISSUE TITLE
Natursystem - gradienter. Viser både KLG og LKM på toppnivå

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1127]
**Describe the bug**
Gradienter på natursytem (NA) viser nå både KLG og LKM. Bør være bare LKM

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem'
2. Click on 'gradienter'
3. See error

**Expected behavior**
se kun LKM

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/54361491-674a2900-4667-11e9-903f-03ddb809b155.png)

**Comment by bjornreppen** [comment]
Er vi i nærheten?
