### ISSUE TITLE
la-id-96 - roter bilde

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1153]
**Describe the bug**

Bildet av la-id-96 er rptert feil. 

**To Reproduce**
1. Go to 'https://data.artsdatabanken.no/Natur_i_Norge/Landskap/Innlandslandskap/Innlandsdallandskap/Dypt_nedsk%C3%A5ret_dallandskap_med_bart_fjell_over_skoggrensen/index.html

**Comment by bjornreppen** [comment]
Det er bestandig noe nytt man ikke har tenkt på.  Fixed med en future prrof fix.

https://stackoverflow.com/questions/19456036/detect-exif-orientation-and-rotate-image-using-imagemagick
