### ISSUE TITLE
Statistikk:  tilpasset tekst for ulike katalogelement

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1156]
Statistikk | Forslag tekst
-- | --
NA | Det er   kartlagt 20.5 km² ferskvannsbunnsystemer. Dette   utgjør 0.7 %av   kartlagte natursystem. Det er observert 2917 ulike arter i områder som er kartlagt som ferskvannsbunnsystemer.
LA | Likt med NA
VV | "Verneområdenavn vernekategori" er xx   km² . Dette utgjør 0.0 % av vernet areal i Norge   inkludert Svalbard og Jan Mayen. Det er observert xx ulike arter i   "Verneområdenavn vernekategori".

**Comment by bjornreppen** [comment]
Utført.

Landkspa venter på statistikk fra nytt landskapskart: https://github.com/Artsdatabanken/grunnkart-dataflyt/issues/70
