### ISSUE TITLE
Søkmeny: Tasten f virker ikke 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-innsyn#1158]
**Describe the bug**
Prøvde å søke på flekkmarihånd, men fikk bare søke på lekkmarihånd.
videre testing viste at bokstaven f blir ignorert. 

**To Reproduce**
1. Go to søkefeltet
2. Click on skriv noe med f i

**Expected behavior**
f blir skrevet

**Desktop (please complete the following information):**
 - windows
 - firefox
 - idk

**Comment by bjornreppen** [comment]
Stygg sak

**Comment by bjornreppen** [comment]
Flott tilbakemelding, var ikke klar over at jeg hadde tabbet meg ut (på noe så grunnleggende)

**Comment by bjornreppen** [comment]
Fixed.
