### ISSUE TITLE
Samle inn data om datasett (metadata, lisenser etc)

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-innsyn#1175]
Behov både fra dataportalen og innsynet (klikk i kart++)

Blokkerer https://github.com/Artsdatabanken/adb-data-portal/issues/12

**Comment by runningbones** [comment]
Har vi en struktur/oppsett på hvilke parametere/attributter som skal angis per datasett?

**Comment by bjornreppen** [comment]
Skjønner ikke hva jeg tenkte da jeg opprettet denne, fortsetter tråden i https://github.com/Artsdatabanken/adb-data-portal/issues/12
