### ISSUE TITLE
Åpne data vs Katalog: lenkebrudd fra søkevindu

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1179]
**Describe the bug**
klikk i søkeboks gir tre alternativ: Landskap, natursystem og katalog. Katalog har endret navn til 'åpne data', og gir følgeliog lenkebrudd ved klikk i alternativ søkevindu.

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/'
2. klikk i  'søkevindu'
3. klikk på katalog
4. see error

**Comment by bjornreppen** [comment]
Klar til test.

**Comment by runningbones** [comment]
Fungerer nå!
