### ISSUE TITLE
søkevindu - natursystem gir 404-ish feil

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1180]
**Describe the bug**

søkevinduets anternativ natursystem gir 404-ish feil

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/'
2. Click on 'søkevindu'
3.velg natursystem

![image](https://user-images.githubusercontent.com/31729342/54984880-12d07300-4fb0-11e9-952d-519bd8a981ff.png)

**Comment by bjornreppen** [comment]
Den slet med å finne ut teksten "Utgjør 100% av natursystem" i teksten for Natursystem... fjernet akkurat den biten av strengen for toppnivånodene.
