### ISSUE TITLE
Nytt host navn for WMS-tjenesten

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-innsyn#1184]
Vi har i dag WMS server på https://nintest.artsdatabanken.no

Denne trenger en et navn uten test ved lasnering, for eksempel: wms.artsdatabanken.no

**Comment by runningbones** [comment]
vi var vel innom kart.artsdatabanken.no i en diskusjon. Ytfroringen med wms er prefix er litt vel begrensende mht til andre ogc-tjenester vi leverer via mapserver (eks wcs/WFS). Anbefaler at Stein avgjør!

**Comment by bjornreppen** [comment]
det er et poeng.. jeg tenkte motsatt.. at vi også serverer kart fra andre steder enn denne, f.eks. raster tiles og vector tiles på http://data.artsdatabanken.no

En annen løsning er å mappe opp både wcs, wfs, og wms mot samme server evt.. da står man også fritt til å senere splitte dem opp.. hvis man ønsket å kjøre en av dem på annen programvare?

**Comment by helemork** [comment]
Denne ser ferdig ut. Lukker den. Bare gjenåpne om jeg tok feil.

**Comment by runningbones** [comment]
Er flyttet, men fungerer fortsatt ikke. Gjenåpnes inntil wms-fungerer på nytt domene.

**Comment by runningbones** [comment]
Gjenstående arbeid i eget repo: https://github.com/Artsdatabanken/ninMapfileCreator/issues
