### ISSUE TITLE
Relasjoner mellom LA, NA og BS-3 er borte

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1186]
**Describe the bug**
Kan ikke se at data fra https://github.com/Artsdatabanken/nin-data/blob/master/Natur_i_Norge/Landskap/Landskapsgradient/relasjon_til_natursystem.csv er tilgjengelig i NiN-kart.

**Comment by bjornreppen** [comment]
Kan det være en grei flyt å sette saken tilbake til deg etter klartgjort så du kan vurdere om tiltaket var ok for så å lukke?

**Comment by runningbones** [comment]
OK!
