### ISSUE TITLE
LA - Navnsetting av kodehierarki i venstrmeny er forskjøvet

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1199]
**Describe the bug**
LA-TI har nå en forskyving av navnsetting av hierarkielementene. Skal være hovedtypegruppe, hovedtype, grunntype. Er nå hovedtype /der det skal være hovedtypegruppe), grunntype (der det skal være hovedtype) og grunntype der det skal være grunntype.
**To Reproduce**

1. Go to 'https://nin.artsdatabanken.no/Natur_i_Norge/Landskap/Typeinndeling'
2. Se venstremargelement 'Hovedtype'. (skal være hovedtypegruppe)
3. See error

**Expected behavior**
katalogelement skal være 'Hovedtypegruppe'

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/55231820-081e1400-5224-11e9-9bfd-58216f632d57.png)

![image](https://user-images.githubusercontent.com/31729342/55231868-23891f00-5224-11e9-9f5b-557e7356df65.png)

**Comment by bjornreppen** [comment]
Request review

![image](https://user-images.githubusercontent.com/281359/55234057-82519700-522a-11e9-8095-30125697128c.png)

**Comment by runningbones** [comment]
Ser bra ut!
