### ISSUE TITLE
Meny/Kart-knappp på bunn

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-innsyn#1201]

**Comment by runningbones** [comment]
Tenker du ned i høyre hjørne?

**Comment by helemork** [comment]
MOBIL:
Utseende ferdig, oppdrag overført til Bjørn

- få knappene til å toggle mellom meny og kart
- skjul meny når man starter på mobil så man kan se kartet også

**Comment by runningbones** [comment]
Mistet noe funksjonalitet på veien, men lar seg nok fixe. Ser på det etter lansering. Manglende funksjonaltet oppdaget så langt: Fjerne "aktive" lag, bytte bakgrunnskart, applikasjonsspesifikk "tilbake".

**Comment by runningbones** [comment]
Kan heller ikke fjerne punktmarkering i kart uten bruk av F5

**Comment by helemork** [comment]
nei, 
- alt i aktive kartlag abben ble gjemt da vi sa den ikke var ferdig. den ble ikke mistet.
- vi har aldri kunnet fjerne punktmarkeringen i kartet
- denne bytte bakgrunnskart har jeg aldri hørt om, men antar det er noe som ligger på aktive kartlag tabben. 
-> å få den tilbake er raskt, den er kun fjernet med display:none; 
tilbake tok vi bort da det er det samme som å trykke back i nettleseren, så den derfor ikke har noen videre funkjson.
