### ISSUE TITLE
ADB - logo i kart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#1219]
**Is your feature request related to a problem? Please describe.**
Kommunikasjonsavdelingen har ytret ønske om en ADBlogo på nin-kart. 

**Describe the solution you'd like**
Foreslår penguin ned i høyre hjørne på kartet.

![image](https://user-images.githubusercontent.com/31729342/55314506-92f05000-546a-11e9-9700-c1b576b90858.png)

**Comment by helemork** [comment]
det ER jo en logo øverst til høyre ??
