### ISSUE TITLE
Lag faktaark for naturtyper

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-innsyn#198]
- Geometri
- Arealer
- Kartleggingsområde
- Kartlegger
- Koder
- ...

**Comment by runningbones** [comment]
Dersom natursystemdatasettet tillater det ville det vært fiffig å inkorporer "faktaark"/ objektspesifikk informasjon i katalogen/treet. Foreslår: "Kartleggingsprogram" som toppnode/forelder, prosjekt som underordnet/childeren.

**Comment by bjornreppen** [comment]
Relatert til https://github.com/Artsdatabanken/kverna/issues/56
