### ISSUE TITLE
 Fungerer ikke i internet explorer!

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#239]
### Issue and Steps to Reproduce
https://grunnkart.firebaseapp.com/ fungerer ikke i internet explorer!

### Versions
20180322
### Screenshots
![image](https://user-images.githubusercontent.com/31729342/37760175-347e5fac-2db6-11e8-9769-9181858ec1fa.png)

### Additional Details
Mulig dette vil endre seg når vi flytter til eget miljø. Mange brukere i offentlig sektor bruker internet explorer som default nettleser, og løsningen bør helst fungerer også i denne nettleserer.

**Comment by bjornreppen** [comment]
Internet Explorer 11?

**Comment by runningbones** [comment]
Usikker på hvilken versjon vi bør sikte på. Kjør debatt!

**Comment by amundn** [comment]
Forsøkt dette uten umiddelbar suksess: https://stackoverflow.com/questions/33828840/symbol-is-undefined-in-ie-after-using-babel

Slik ser det ut i IE11:
![image](https://user-images.githubusercontent.com/13641108/38294615-b499743a-37eb-11e8-9b41-c98a9f384a11.png)

**Comment by amundn** [comment]
Fant ut at babel-polyfill måtte importeres før react

**Comment by bjornreppen** [comment]
Internet Explorer is a compatibility solution. We’re not supporting new web standards for it and, while many sites work fine, developers by and large just aren’t testing for Internet Explorer these days. They’re testing on modern browsers. https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732

**Comment by bjornreppen** [comment]
Sjekket ut med NINA og der har alle brukere Chrome og Edge installert i tillegg til IE11.  Mulig vi heller kan bidra til å lære dem å fyre opp en mer moderne browser?  Å lage løsning kompatibel løsning med IE11 blir stadig mer krevende etterhvert som nye finesser som ikke finnes i IE11 tas i bruk i komponenter og rammeverk.  Spørsmålet er om vi er best tjent med å lage en kompatibilitetsløsning som bremser utviklingen da flere brukere kan slippe unna med å bruke utdatert teknologi, eller om vi skal bidra til at flere brukere bytter over til moderne verktøy?
