### ISSUE TITLE
Katalog - visning av koder

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#384]
**Is your feature request related to a problem? Please describe.**
Ved navigering i katalogen vises i dag kun den "siste" relevante del av kodestreng. (Ikke parent)

**Describe the solution you'd like**
dette kan bli noe forvvirende for brukere, særlig på dteder hvor katalogen viser sammensetninger av koder som ikke har samme parent. tror derfor vi må vise parentkode og kankje til og med grandparent i katalogen. dette kommer særlig til syne ved navigering i f.eks. https://grunnkart.firebaseapp.com/katalog/na/ht/dg/0 

![image](https://user-images.githubusercontent.com/31729342/40545146-10890adc-602b-11e8-94ff-9f576f95125a.png)

**Comment by amundn** [comment]
Problemet var vel litt at kodene ble lange og tok mye plass.. Hva tror du om å vise hele koden som tooltip ved hover over koden? 
![image](https://user-images.githubusercontent.com/13641108/41034192-2aab8dba-6989-11e8-859a-91b7ea102b83.png)

**Comment by runningbones** [comment]
Er ikke udelt positiv til tooltip/hover. Hva med om vi legger til kode (elementkode) i navigasjonslenkene øverst, samt informasjon om målestokk under fakta? Mockup:
![image](https://user-images.githubusercontent.com/31729342/41035851-504afaf6-698e-11e8-84a6-01e47c8f6865.png)

**Comment by amundn** [comment]
Delvist addressert i https://github.com/Artsdatabanken/ratatouille/pull/445

**Comment by runningbones** [comment]
Ser bra ut i navigasjonslenkene øverst, er det mulig å legge på målestokkkoden foran tall i opplisting av childeren? (ser det er lagt på tooltip :)) 

![image](https://user-images.githubusercontent.com/31729342/41096551-3e9eadc6-6a55-11e8-8c82-a20645bd6a51.png)

EN annen enhancment kan være å legge på målestokkboktav i navigasjonslenkene øverst.

**Comment by amundn** [comment]
Skulle hatt en enkel måte å fått tak i målestokk-koden på. Et alternativ er å trekke den ut fra selve koden. 
Er det entydig hvordan den ser ut i kodene? Ser alle slik ut f.eks: "NA_T15-E-1" med "bokstav strek tall" til slutt, eller kan det være flere nivåer videre nedover?

**Comment by amundn** [comment]
Koden som splitter opp kodene ligger i typesystem-prosjektet.  
`typesystem.splittKode(kode)`

**Comment by bjornreppen** [comment]
Bare å hacke her:
https://github.com/Artsdatabanken/typesystem/

PS: Bruk `yarn commit` istedet for git commit, for hjelp med semantic versioning - ny release i npmjs lages automagisk basert på commit streng eller valgene man gjør i menyen i yarn/npm commit.

**Comment by runningbones** [comment]
@amundn : Mener kodene skal være entydig mht måkestokk:   
`hovedtypegruppe(bokstav)-hovedtypenummer-måletokk(bokstav)-kartleggingsenhetsnummer` (unntakene er når det grunntyper, da er det ikke en bokstav etter hovedtypenummer, men rett på grunntypenummer.

**Comment by amundn** [comment]
@runningbones: Hvilke målestokkbokstaver skal jeg ta hensyn til: Denne koden laget trøbbel i parsingen min, her er vel ikke A målestokk?
BS_1AG-A-0

**Comment by runningbones** [comment]
@amundn bra observert. Det jeg skrev mht til entydighet og målestokk gjelder kun naturområdetyper, ikke beskrivelsessystemet.

**Comment by amundn** [comment]
men trenger jeg sjekke for A-E eller kun C og E ?

**Comment by amundn** [comment]
@bjornreppen : vil endring av splitt-funksjonen lage tull for henting fra firebase? Ser at endringen min fører til en test som feiler: AssertionError [ERR_ASSERTION]: 'NA/T/44/E-1' == 'NA/T/44/E/1'

**Comment by runningbones** [comment]
@amundn : per nå foreligger kun kartleggingsdata i basen for data med `C or E`
