### ISSUE TITLE
Diagnostiske arter - mangler i innsyn

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#457]
**Describe the bug**
Diagnostiske arter ligger i grunnlagsdata for `ogapi,` men kommer ikke med i spørring fra innsyn

**Comment by bjornreppen** [comment]
Aggregeres opp fra grunntypene som vi ikke viser i løsningen til kartleggingsenhetene

**Comment by runningbones** [comment]
Viktigst med ren kobling i natursystemhierarki, men gjerne også LKM...

**Comment by bjornreppen** [comment]
Løst i https://github.com/Artsdatabanken/kverna/pull/199
