### ISSUE TITLE
UTM i leaflet

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#521]
**Is your feature request related to a problem? Please describe.**
Avklare utfordringer/løsninger på bruk av utm 33 i leaflet

**Comment by jarped** [comment]
* [ ] Sjekke om https://github.com/kartena/Proj4Leaflet kan brukes

**Comment by bjornreppen** [comment]
Konkludert med at UTM vha proj ikke er veien å gå.  Heller lage UTM tile sets.

Videre diskusjon i https://github.com/Artsdatabanken/nin-innsyn/issues/526
