### ISSUE TITLE
Klikk i kart/punktinfo

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#522]
**Describe the bug**
Venstreklikk i kartet gir ingen info

**To Reproduce**
1. Go to https://naturinorge.firebaseapp.com
2. Venstreklikk i kartet
3. See error

**Expected behavior**
info fra alle lag i punktet+wms fra Mdir/kartverket

**Comment by runningbones** [comment]
Av og til flyter punktet i kartet når jeg zoomer/panorerer etter klikk https://artsdatabanken.slack.com/?redir=%2Ffiles-pri%2FT5EEE5ZNE-FC6T11S57%2Fdownload%2Fnatur_i_norge_-_google_chrome_13.08.2018_12.35.14.mp4

**Comment by bjornreppen** [comment]
Denne er blokkert av [rasterQ#2](https://github.com/Artsdatabanken/rasterQ/issues/2)

**Comment by runningbones** [comment]
mangler metadata fra NA.

**Comment by bjornreppen** [comment]
Fikset.
