### ISSUE TITLE
Farger - Rødlista

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#564]
**Is your feature request related to a problem? Please describe.**
farger på RL bør samsvare med farger brukt på kategorier i RL-arter 2015.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/31729342/44449120-8dd24500-a5ed-11e8-80a2-9ee145f464a3.png)

**Comment by bjornreppen** [comment]
Så dette er altså fargene vi skal bruke?  Nei, jeg er ikke helt fornøyd, må si det.
![image](https://user-images.githubusercontent.com/281359/44487686-3072de00-a657-11e8-8caa-d084a6d96ca6.png)

IUCN sine farger er kanskje littegrann enklere å skille.
![image](https://user-images.githubusercontent.com/281359/44487705-3ff22700-a657-11e8-8723-629cd223bf5d.png)

Se gjerne https://uu.difi.no/krav-og-regelverk/losningsforslag-web/bruk-av-farger

**Comment by runningbones** [comment]
Enig i at ADBs farger bør være enklere å skille, tar en diskusjon med Rødlistekongen i morgen!
