### ISSUE TITLE
Metadata - klikk i kart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#670]
**Is your feature request related to a problem? Please describe.**
Vi trenger en enhetlig måte for at brukeren skal kunne se metadata (data om) i løsningen

**Describe the solution you'd like**
Klikk i kart genererer i dag en vining av alle "koder" i punktet. Her kan bruker få et valg: enten se mere om kodene (ved å klikke videre på kodene i lista i venstremenyen), eller å se metadata om data i punktet. Mulig vi må introdusere en knapp/toggle/tab "om kode/om data" (dårlig begrep)

**Comment by runningbones** [comment]
Forslag: Lag "toggle switch" under visning av "alle" data i punktet (klikk i kart), hvor brukeren kan velge: "vis bare fra aktive kartlag"

**Comment by bjornreppen** [comment]
Grunnleggende på plass, men videreutvikles vel i andre issues?
