### ISSUE TITLE
Metadata.json MBtiles

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#901]
https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/wiki/Help

**Comment by bjornreppen** [comment]
Fikk du åpna tilesets fra qgis?

**Comment by bjornreppen** [comment]
Tilejson som kan pekes på fra QGIS ligger for eksempel her for Fastmark: https://data.artsdatabanken.no/Natur_i_Norge/Natursystem/Fastmarkssystemer/polygon.3857.mbtiles?tilejson
