### ISSUE TITLE
Landskap - vinsing av alle hovedtyper som default

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#986]
**Is your feature request related to a problem? Please describe.**
Trond S. ønsker at første nivå for visning av Landskapsakartet/default visning ved "klikk i katalog - Landskap" skal vise alle hovedtyper samtidig. 

Nå vises først hovedtypegrypper, deretter hvoedtyper per hovedtypegruppe. 

**Describe the solution you'd like**
Lar seg gjør i dag, men krever at man legger til alle tre hovedtypegruppe som aktive kartlag.

![image](https://user-images.githubusercontent.com/31729342/52408566-660b6680-2ad3-11e9-9f1f-3bc11fc90ba0.png)

**Describe alternatives you've considered**
Dette bryter med den gjennomgående hiearkiske inngangen i løsningen, men deler Tronds synspunkt om at den eneste helhetlige viningen av LA-typer er så aggregert at den kamuflerer mangfoldet i datasettet. Kjør debatt!

**Comment by runningbones** [comment]
kan det løses noe ala:
![image](https://user-images.githubusercontent.com/31729342/52411549-8e4b9300-2adc-11e9-9d3f-068989fb4014.png)

**Comment by helemork** [comment]
Status?

**Comment by bjornreppen** [comment]
So many issues, so little time... kunne trenge hjelp med styling... 

![image](https://user-images.githubusercontent.com/281359/55293576-1e7cc900-53f8-11e9-8b21-2d4356604a0f.png)

**Comment by runningbones** [comment]
Ser lovende ut! Viktigere med funksjonen er der, enn at den er dødslekker!

**Comment by bjornreppen** [comment]
Produsert av https://github.com/Artsdatabanken/rasterize-mbtiles-from-geojson
