### ISSUE TITLE
Klikk i kart - lenke til riktig katalogelement

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-innsyn#988]
**Describe the bug**
Klikk i kart gir treff, med visning i venstremarg. Ved klikk på element i venstremarg kommer man i dag ikke til riktig element i katalogen.

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/?lng=10.13341126051588&lat=63.380512821715506'
2. Click on 'Landskap'
3. See error

**Expected behavior**
Komme til riktig landskapstype i katalogen

**Comment by runningbones** [comment]
Nå fører klikk i kart til :Visning

**Comment by bjornreppen** [comment]
![klikk](https://user-images.githubusercontent.com/281359/53328118-8ddb3680-38e9-11e9-844c-6cbd1ac5a2cb.gif)
